theme: jekyll-theme-minimal
title: お道具箱
description:  >- # this means to ignore newlines until "baseurl:"
  mainly about Julia lang, statistics, stochastic process, and finance.

email: 'yuki.fhs(at)gmail.com'
logo: assets/LOB_describe_NoText.png

google_analytics: G-E8M7KJ8BVB
repository: "yukki-jpn/yukki-jpn.github.io"
author:
  name: Yuki Sato
  email: 'yuki.fhs(at)gmail.com'

#github : [metadata]
